tokenizer_name: 'monologg/kobert'
model_name: 'monologg/kobert'
train_data_path: '../data/train.csv'
val_data_path: '../data/val.csv'
test_data_path: '../data/test.csv'
model_path: './models
output_dir: './results'

# training arguments
output_dir: './results'
max_len: 256
epochs: 5
steps: 1000
batch_size: 32