tokenizer_name: 'monologg/kobert'
model_name: 'monologg/kobert'
train_data_path: '../new_data/reduced_train_v2.csv'
val_data_path: '../new_data/reduced_val_v2.csv'
test_data_path: '../new_data/reduced_test_v2.csv'
model_path: './models'
output_dir: './results'

# training arguments
output_dir: './results'
max_len: 256
epochs: 5
steps: 500